M48
; DRILL file {KiCad 8.0.0} date 2024-02-29T15:38:22+0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-02-29T15:38:22+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X29.825Y6.03
X34.675Y6.03
T2
X29.525Y3.0
X34.975Y3.0
M30
